# Generated by Django 4.2.8 on 2024-05-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='graph',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='country',
            name='rate',
            field=models.FloatField(),
        ),
    ]
