# Generated by Django 4.2.8 on 2024-05-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
